---
layout: post
title: Digital Monopolies and Dictatorship
categories:
- Future of the Internet
tags: []
status: publish
type: post
published: true
meta:
  _wpas_done_2892683: '1'
  _publicize_done_external: a:1:{s:8:"facebook";a:1:{i:722750362;b:1;}}
  publicize_twitter_user: ozziegooen
  publicize_reach: a:2:{s:2:"fb";a:1:{i:2892683;i:871;}s:2:"wp";a:1:{i:0;i:2;}}
  _elasticsearch_indexed_on: '2013-03-04 09:56:59'
---
Facebook may be colored blue because Mark Zuckerberg happened to be <a href="http://www.nybooks.com/articles/archives/2010/nov/25/generation-why/?pagination=false">red-green colorblind</a>.  Now over 1 billion people see a blue page for 5+ hours a month because of it.  This is one small and rather innocent example of what happens when one person gets incredible power, which the web enables in ways never really seen before.

[caption id="" align="alignleft" width="210"]<a href="http://bowlabs.files.wordpress.com/2013/03/220px-ishihara_9.png"><img class="size-full wp-image " id="i-556" title="Red-Green Colorblindness Test" alt="Image" src="http://bowlabs.files.wordpress.com/2013/03/220px-ishihara_9.png?w=210" width="210" height="210" /></a> Red-Green colorblindness test[/caption]

[caption id="" align="alignleft" width="383"]<a href="http://bowlabs.files.wordpress.com/2013/03/facebook-messages1.jpg"><img class="wp-image " id="i-558" alt="Image" src="http://bowlabs.files.wordpress.com/2013/03/facebook-messages1.jpg?w=710" width="383" height="215" /></a> Facebook, with no red or green[/caption]

In <a href="http://www.amazon.com/The-Facebook-Effect-Company-Connecting/dp/1439102120/ref=sr_1_1?ie=UTF8&amp;tag=libraryextension-20&amp;camp=211189&amp;creative=9325&amp;linkCode=as2&amp;creativeASIN=1439102120">The Facebook Effect</a>, David Kirkpatrick mentions a few stories of Mark Zuckerberg analyzing user behavior over social networks.  What Mark realized, very early on, was that social networks had incredible economies of scale.  I don't think the book mentioned <a href="http://en.wikipedia.org/wiki/Reed's_law">Reed's Law</a>, but I do think it is particularly relevant.

From Wikipedia:
<blockquote><b>Reed's law</b> is the assertion of <a title="David P. Reed" href="http://en.wikipedia.org/wiki/David_P._Reed">David P. Reed</a> that the <a title="Utility" href="http://en.wikipedia.org/wiki/Utility">utility</a> of large <a title="wiktionary:Network" href="http://en.wiktionary.org/wiki/Network">networks</a>, particularly <a title="Social network" href="http://en.wikipedia.org/wiki/Social_network">social networks</a>, can <a title="Exponential growth" href="http://en.wikipedia.org/wiki/Exponential_growth">scale exponentially</a> with the size of the network.</blockquote>
Phrased differently, social networks are essentially incredibly monopolistic.  While there used to be competition at the start of the social network space, the game is now rigged and the king of the hill is miles up.  It's as if, for some strange reason, the most popular coffee shop in San Francisco by 2014 would gain permission to replace 80% of all international global coffee shops.  Even if there was an initially fair playing ground, and no obvious unfair play, the results can be very scary.

Now Facebook has over one billion users, who spend an average of over <a href="http://www.insidefacebook.com/2012/03/27/users-spent-more-than-10-5b-total-minutes-per-day-on-facebook-in-january-not-including-mobile-use/">10 minutes a day</a> on the service.  That adds up to a lot of time by a lot of people.  I spend more time with Facebook personally than I do doing my taxes or relating to my government.  In many ways, Facebook is more important than most world governments, especially given how universal it is.  It's far larger and time consuming than the vast majority of social structures now and throughout all history.

[caption id="attachment_561" align="aligncenter" width="328"]<a href="http://bowlabs.files.wordpress.com/2013/03/comscore-share-time-spent-on-socnet-sites-in-dec-feb2013.png"><img class="wp-image-561  " alt="Time Spent on Social Networking Sites" src="http://bowlabs.files.wordpress.com/2013/03/comscore-share-time-spent-on-socnet-sites-in-dec-feb2013.png" width="328" height="214" /></a> Time Spent on Social Networking Sites[/caption]

The 10 minutes on Facebook per day leaves out the influence of Facebook on the rest of the web, where their social buttons and integration is heavily tied to sites that I bet most people spend way more time on.  Facebook has a strange and powerful control of the future of the internet.  They ask and millions of websites put up metadata tags in a way that seems unparalleled to anything seen before.

Even after IPO, Mark Zuckerberg still owns over <a href="http://www.newyorker.com/talk/financial/2012/05/28/120528ta_talk_surowiecki">58% of all of Facebook voting shares,</a>  He effectively controls everything Facebook.  While it is refreshing that he wasn't screwed (as happens with many entrepreneurs), this high level of control is frightening.  Thousands of people worked on the product for possibly tens of thousands of man years, millions of people have directly participated in making the platform so incredibly successful, but because of the strange way the first few years played out Mark was able to keep over 58% of absolutely all control to himself.  It's true that he "only" owns about 20% of the equity, but does this matter in comparison?

[caption id="attachment_565" align="aligncenter" width="302"]<a href="http://bowlabs.files.wordpress.com/2013/03/funny-facebook-pigs-talking.jpg"><img class="wp-image-565 " alt="funny-Facebook-pigs-talking" src="http://bowlabs.files.wordpress.com/2013/03/funny-facebook-pigs-talking.jpg" width="302" height="242" /></a> A particularly popular political comic about Facebook[/caption]

What does it mean when one person possesses control over millions like this? Online locations are not that much different from physical ones.  Facebook has become a fundamental technology relied on by hundreds of millions of people.  It doesn't seem much different or less important than the beginnings of the electric system or telephone network.  And one guy owns it.  When AT&amp;T, controlled by a small management team, had too much power the government split it up.  It was then worth about one half as much as Facebook now (adjusted for inflation).

Mark seems to be a benevolent dictator.  He's probably much better than the alternative of a set of mediocre managers and board members with interests mixed between corporate profit and self promotion, which is the standard in the industry.  People admit that Facebook would have gotten sold a long ago without him, and I believe that his vision for the future of Facebook is more long-term than anyone else conventionally put in power of technical companies.  But it does open up the question of what government systems we think are just and reasonable.

[caption id="attachment_563" align="aligncenter" width="314"]<a href="http://bowlabs.files.wordpress.com/2013/03/facebook-protest-003.jpg"><img class="wp-image-563 " alt="One of many Facebook protests, that no one really paid attention to or cared about." src="http://bowlabs.files.wordpress.com/2013/03/facebook-protest-003.jpg" width="314" height="187" /></a> One of many Facebook protests, that no one really pays attention to or cares about.[/caption]

When Rome changed to a dictatorship (essentially), it started out quite well.  <a href="http://en.wikipedia.org/wiki/Augustus_Ceasar">Augustus</a> was a smart guy who was essentially an effective benevolent dictator.  But future leaders were not so kind or intelligent, and everything fell apart shortly thereafter.  The one saving grace with regards to Facebook is that because of technological disruption it is quite possible that Facebook's empire will fall or become obsolete before they run into the worst problems of incredibly personal control.  But it's not certain and is definitely not a good long term fail safe.

The question of the power roles of founders is the fundamental question of <a href="http://www.nybooks.com/articles/archives/2010/nov/25/generation-why/?pagination=false">Political Philosophy</a>.  While academics debate this in ivory towers, coders are on the ground making important decisions now.  And they seem to be deciding on <a href="http://en.wikipedia.org/wiki/Benevolent_Dictator_for_Life">dictatorships</a> and anarchies.  For all the talk of how we love democracy, there's surprisingly little of it being created.  We jam Democracy down the throats of tiny countries in Africa but don't seem to notice it for the emergence of gigantic digital communities and infrastructure many times the size.  There are some reasons for this of course, but I believe this represents a serious case of cognitive dissonance that should be rigorously investigated and understood.  My honest guess is that we'll determine that we very much need to disperse power online, but also realize that Democracy isn't as important or holy to us as we'd like to believe.

[caption id="attachment_567" align="aligncenter" width="390"]<a href="http://bowlabs.files.wordpress.com/2013/03/untitled-1.png"><img class=" wp-image-567 " alt="Mark doesn't dress like this, but he possesses far more power than perhaps all who have." src="http://bowlabs.files.wordpress.com/2013/03/untitled-1.png" width="390" height="315" /></a> Mark doesn't dress like this, but he may possess more power than almost all who have.[/caption]

Facebook even attempted Democracy, but did it poorly.  As in, worse than China or Iran poorly (though, to be fair, not with nearly as dire consequences so far).  They put their new data use policy and statement of rights up for vote with the general public.  350,000 users ended up voting, and 6/7th of them voted "no".  Unfortunately Facebook required that 300 million+ people voted for quorum by the closing date, which obviously did not happen, so Facebook went ahead and made the changes anyway.  If something similar were to happen to a third world country we'd consider them completely corrupt and juvenile.  Here it happens to us and we don't care to notice.  Read <a href="http://arstechnica.com/business/2012/06/whopping-00038-of-facebook-users-vote-on-data-use-policy-change/">this</a> and <a href="http://www.buzzfeed.com/mtpiii/the-end-of-the-facebook-democracy">this</a> for more info.

The bottom line is that now, millions of people have no say in a community they are all contributing to.  In fact, they <a href="http://www.nbcwashington.com/the-scene/events/Facebook-Users-on-Verge-of-Mutiny-130288643.html">violently oppose</a> every single update Facebook gives them, but the one ruler doesn't care.  Perhaps he shouldn't.  But we need to do some careful considering of what power structures and governments we are willing to accept and promote.  We also should re-consider what democracy really is and how important it should be.  Things will only get more messy from here.

&nbsp;
