---
layout: post
title: The Internet is "Real Life"
categories: []
tags: []
status: publish
type: post
published: true
meta:
  _publicize_pending: '1'
  _wpas_done_2892683: '1'
  _publicize_done_external: a:1:{s:8:"facebook";a:1:{i:722750362;b:1;}}
  publicize_twitter_user: ozziegooen
  _elasticsearch_indexed_on: '2013-03-13 01:25:39'
---
<p>The idea that the physical world some of us normally live in is "real" in any objective or absolute sense is a bit out of date and silly.  It seems like there's a decent chance we may be in <a href="http://news.discovery.com/space/are-we-living-in-a-computer-simulation-2-121216.htm">a simulation</a>, and likely a greater chance we're "in" something we couldn't understand or comprehend if we were to find evidence for it.</p><p><a href="http://bowlabs.files.wordpress.com/2013/03/avatar.jpeg"><img class="size-full wp-image" id="i-637" alt="Image" src="http://bowlabs.files.wordpress.com/2013/03/avatar.jpeg?w=249" /></a></p><p>So I'm sick of people considering online living as absolutely inferior to "physical" living.</p><p>There are some <a href="http://www.amazon.com/Alone-Together-Expect-Technology-Other/dp/0465031463/ref=sr_1_1?ie=UTF8&amp;tag=libraryextension-20&amp;camp=211189&amp;creative=9325&amp;linkCode=as2&amp;creativeASIN=0465031463">valid reasons</a> for how people sometimes use specific technologies to unintentionally alienate and permanently damage themselves.  But these are specific to our existing state and definitely not to "all of technology" or the entire concept of the internet.  Intellectuals used to warn that people were absorbed in the artificial world of books which were tearing them from "reality".  Now books are associated with goodness and intellect so no one really cares any more.  The same has yet to happen to the internet.</p><p>Gamers sometimes facilitate this illusion by using the term "IRL" (In Real Life) to refer to the non-gaming world.  I think this may be a destructive term.  The world they are referring to may not be less real than the one they are in, only something very different.  </p><p>This does leave the awkward question of what to exactly call this plane of existence.  It seems strange to call it a reality, unless one considers 'reality' a loose term that is expanded to online universes and ones we don't know about.  Comic writers used the word "universe" to discern the places between different stories, but this signifies them as non-combining entities, while the 'realities' I'm referring to often take place somewhat inside each other.  I'm sure this is one bit that went into the term IRL as not a definitive one but as something people will use until someone can come up with something better.</p><p>One awesome quote from Wikipedia:<br /><br />"Some <a title="Sociologist" href="http://en.wikipedia.org/wiki/Sociologist">sociologists</a> engaged in the study of the Internet have predicted that someday, a distinction between online and real-life worlds may seem "quaint", noting that certain types of online activity, such as sexual intrigues, have already made a full transition to complete legitimacy and "reality".<sup id="cite_ref-Slater_2-0"><a href="http://en.wikipedia.org/wiki/Real_life#cite_note-Slater-2">[2]</a>"</sup></p><p>[youtube https://www.youtube.com/watch?v=n-M4kPxd03k&w=853&h=480]</p><p> </p>
