---
layout: post
title: Morality is Still on Very Flaky Foundations
categories:
- Rationality and Uncertainty
tags: []
status: publish
type: post
published: true
meta:
  _wpas_done_2892683: '1'
  publicize_twitter_user: ozziegooen
  _wp_old_slug: morality-is-still-on-very-flaky-foundations
  _publicize_done_external: a:1:{s:8:"facebook";a:1:{i:722750362;b:1;}}
  publicize_reach: a:2:{s:2:"fb";a:1:{i:2892683;i:958;}s:2:"wp";a:1:{i:0;i:3;}}
  _wpas_skip_2892683: '1'
  _elasticsearch_indexed_on: '2013-05-10 22:02:28'
---
The modern effective altruist and utilitarian movements have crusaded against intuition with rationality, but have arrived at a very awkward ground in between the two.  Advancing means facing an outcome that seems unbelievably strange and unfavorable, yet retreating would mean complete moral disillusionment and defeat.  And yet any stance in between the two is flawed due to the same factor that both movements were made to fight against.

Let me explain.

<strong>The Original Problem</strong>

Most people I know consider themselves to be relatively moral individuals, no matter what kind of morality they ascribe to.  Almost every single piece of literature we read and a large majority of politics hangs onto the ideal of moral righteousness in one form or another.  So when people like <a href="https://en.wikipedia.org/wiki/Peter_Singer">Peter Singer</a> and <a href="https://en.wikipedia.org/wiki/Eliezer_Yudkowsky">Eliezer Yudiskowsky</a> goes out and states that <a href="http://www.utilitarian.net/singer/by/199704--.htm">conventional morality is bullshit</a>, people <a href="https://en.wikipedia.org/wiki/Peter_Singer#Criticism_of_Singer">freak out</a>.

The basic argument goes that we typically judge morality based on initions we have, rather than facts and rigorous analysis.  And this leads to <a href="http://intelligence.org/files/CognitiveBiases.pdf">strange things</a>, like seeking moral vengeance against people who kill one or two individuals, while not blaming people with the ability to save millions of lives but not doing so.  Our intuitions were created from evolution optimized for cavemen, and whatever social norms and media we are subjected to.  They are are faulty due to numerous <a href="http://intelligence.org/files/CognitiveBiases.pdf">cognitive biases</a>, and a moral standing upon them is difficult to de-couple from complete <a href="https://en.wikipedia.org/wiki/Moral_relativism">moral relativism</a>, an incredibly undesirable state for intellectual morality.

So in a way, most modern morality is built upon strong intuitions.  The issue is that these intuitions are inconsistent and provably flawed for the modern era.  If we live out our entire lives and build societies based on these moral intuitions, then we are arguably doing almost everything on top of some very shaky foundations.

I'll use a few comics from the excellent <a href="http://www.amazon.com/Logicomix-An-Epic-Search-Truth/dp/1596914521/ref=sr_1_1?ie=UTF8&amp;qid=1368222515&amp;sr=8-1&amp;keywords=logicomix">Logicomix</a> to help illustrate my point.  That book detailed the mathematical venture into complete proof and certainty against intuition, and I feel like that was very similar to what we are now going through with morality.

<a href="http://bowlabs.files.wordpress.com/2013/05/basic.png"><img class="alignnone size-full wp-image-808" alt="basic" src="http://bowlabs.files.wordpress.com/2013/05/basic.png" width="637" height="313" /></a>

<strong>Rationality to the Rescue</strong>

How to we fix this?  The existing fight against moral intuition has come from  utilitarianism and effective altruism.  These groups try to deduce why our important intuitions exist to help prove which ones are morally true and which are cultural and/or evolutionary artifacts.  Utilitarianism was somewhat of an attempt to create an overal structure that is somewhat intuitively reasonable but most importantly, numerical.  Basically, we define "goodness" in some way (often defined as "happiness", but possibly "awesomeness" or any other word you might consider to be a reasonable ultimate human goal) and define moral good as to whatever reaches that.  The Effective Altruist group kind of grew out of this to help define good life practices (like donating to efficient charities rather than cute ones) that help optimize this number.  Often this seems unintuitive (for example, it may be very justifiable to not give to homeless people close to you and instead donate to charities you will never see), but can be defended well with math.

Basic practices here are to do things like encouraging people to live lives that favored large donations to efficient charities, rather than typical bleeding-heart goodwill.  Others work on projects "orders of magnitude" more useful than anyone else in mainstream society, including researching the Singularity, ending human aging, and human computer uploading.  On paper these are incredible useful activities, because they are so much better than what is mainstream.  People doing these can feel quite morally superior to the rest of society, and still feel the logically reasonable ability to complain morally about war criminals and resist moral relativism.
<p style="text-align:center;"><a href="http://bowlabs.files.wordpress.com/2013/05/line.png"><img class=" wp-image-810 aligncenter" alt="line" src="http://bowlabs.files.wordpress.com/2013/05/line.png?w=922" width="517" height="165" /></a></p>
<p style="text-align:left;">Above shows a basic diagram of how I see the the "morality" of individuals based on something like utilitarianism.  While I chose "Expected Average Lives Saved (or Equivalent)", what we are really talking about is some measure of goodness.  Peter Singer well reasons that people who choose not to do good should be faced with similar scrutiny as those who choose to do harm.  Likewise, the only "moral" position is to do as "much as possible", which is generally defined as "Effective Altruism", that box on the right.  The groups mentioned all fit into this general category, and from their perspective, they are all somewhat in the same position.</p>
<p style="text-align:left;"><strong>Trouble In Paradise </strong></p>
<p style="text-align:left;">This all works out well, until even more effective rationalists appear.  Perhaps they come in the form of strict <a href="https://en.wikipedia.org/wiki/Machine_Intelligence_Research_Institute">AI-risk reducers</a>, or something else we haven't seen yet.</p>
<p style="text-align:center;"><a href="http://bowlabs.files.wordpress.com/2013/05/line2.png"><img class=" wp-image-812 aligncenter" alt="line2" src="http://bowlabs.files.wordpress.com/2013/05/line2.png" width="630" height="165" /></a></p>
<p style="text-align:left;">Keep in mind that each bar is an order of magnitude greater than the last one, so in comparison to the "more effective altruists", the "effective altruists" look 10x to 100x as suboptimal.  The "effective altruists" claim that regular people were imoral because they only save 1 life rather than 1000 (resulting in 999 unnecessary deaths), but here come this other group complaining that the "effective altruists" are saving 1k rather than 100k lives (resulting in 99,000 unnecessary deaths).</p>
<p style="text-align:left;">The trouble is that one of the main justifications for the work of many effective altruists is that they are much "better in comparison" to everyone else.  Being "better" only makes one "good" when one only cares about comparisons.  Was the "best" Nazi a "good" person, because he or she should be compared to other Nazis, or a "bad" one, because we happen to have non-nazis to compare him or her to?  If one's morality is rooted in its comparison to that of other's, then one can go from "good" to "bad" just by the appearance of a new group.</p>
<p style="text-align:left;"><strong>The Annoying Pupils</strong></p>
<p style="text-align:left;">Rejecting intuitive solutions presents all kinds of other nasty issues, if you were to take it to the extreme.  This would mean that there is almost no point where one can really say "oh, this makes basic sense, so I'll accept this premise and work from there".  And when one decides to create an entire personal philosophy off of preferring rationality to intuition, the rabbit hole can go much deeper than individual prefers.  At every level of logical thought, there can be someone new who complains that it's not completely rational, and little rational reason for proving that it shouldn't be.</p>
<p style="text-align:left;">Typically when we make logical decisions, we ultimately come down to a few intuitive things.  For example, we may optimize a business strategy for revenue, but we still make the intuitive decision that revenue is what we should be optimizing for.  One can go further and "rationally" explain why revenue is statistically expected to be the best way for the business to grow, but from there, there's the intuitive assumption that the growth of the business is a good thing.  Several other intuitive assumptions are probably made in the rest of the model as well, it is almost impossible to make a complete model without them.</p>
<p style="text-align:left;">So the big question is how to decide where to make intuitive judgements vs. rational ones.  But to decide this question, there should ideally be a rational answer.  If there were an intuitive one, that would mean an intuitive foundation, which leads us back to where we started.  And finding a rational answer that we agree upon can be incredibly difficult.</p>
<p style="text-align:left;"><strong>Levels of Goodness </strong><b>Intuition</b></p>
<p style="text-align:left;">Let's begin with an example.  When deciding on donating to a poorly run childcare charity compared to a well run one, the choice is relatively obvious within most definitions of "good".  So within many definitions of "good", the answer could be made relatively easily.</p>
<p style="text-align:left;">But take something more extreme: what if we need to choose between the lives of 4 cows compared to 1 human being?  Or 1000 <a href="http://www.utilitarian-essays.com/humane-insecticides.html">insects</a> (expected, though highly unlikely) compared to 1 human being?</p>
<p style="text-align:left;">The typical answer that I've heard for this, is to make an intuitive judgement about how important a cow is to a human.  Perhaps cows are 1/3rd as intelligent, then 4 cows "utility" would be greater than that of one human.  But the "utility" is a very difficult thing to define, and many people really only care to optimize human utility.</p>
<p style="text-align:center;"><a href="http://bowlabs.files.wordpress.com/2013/05/human.png"><img class="wp-image-816 aligncenter" alt="human" src="http://bowlabs.files.wordpress.com/2013/05/human.png" width="560" height="227" /></a></p>
<p style="text-align:left;">Even worse is when this taken to the computational extreme.  Many futurists advocate human brain <a href="http://wiki.lesswrong.com/wiki/Mind_uploading">uploading to machines</a>.  They claim that simulated cognition is equivalent to physical cognition, and simulations of us could be much better taken care of than real ones.  Others find this scenario as repulsive and wrong.</p>
<p style="text-align:center;"><a href="http://bowlabs.files.wordpress.com/2013/05/physical.png"><img class=" wp-image-817 aligncenter" alt="physical" src="http://bowlabs.files.wordpress.com/2013/05/physical.png" width="560" height="227" /></a></p>
<p style="text-align:left;">Some take another step and say that instead of us being uploaded into an amazing world, we should go straight to <a href="http://wiki.lesswrong.com/wiki/Wireheading">wireheading</a>, into a state where our brains get pure "happiness" without realized experiences.  This is very controversial but seems very counter-intuitive and strange to other values we have.  As <a href="http://wiki.lesswrong.com/wiki/Wireheading">lesswrong</a> points out,</p>

<blockquote>
<p style="text-align:left;">"A civilization of wireheads "blissing out" all day while being fed and maintained by robots would be a state of maximum happiness, but such a civilization would have no art, love, scientific discovery, or any of the other things humans find valuable."</p>
</blockquote>
<p style="text-align:left;">Some take this further and say that if simulations of us are more "optimal" than us, then wouldn't simulations of even "happier" beings be more optimal?  Or perhaps an A.I. should just simulate "pleasure" itself, essentially ending living sentience as we know it and replacing it completely with machines simulating things we can not now possibly imagine.  There are some that feel like for any given definition of "happiness", this would be preferable, but others who feel like it is morally wrong for us because of its lack of most existing human values.</p>
<p style="text-align:center;"><a href="http://bowlabs.files.wordpress.com/2013/05/terminator.png"><img class="wp-image-818 aligncenter" alt="terminator" src="http://bowlabs.files.wordpress.com/2013/05/terminator.png" width="560" height="227" /></a></p>
<p style="text-align:left;">The one "completely rational" utilitarian answer that makes sense (is intuitive as being rational) to me is just that, that ultimately the most utility would come from replacing all current sentience with completely artificial beings (or being).  Essentially, not only letting the Matrix or Terminator overlords win the fight, but rushing for this to happen, fighting for it, and doing whatever is necessary.  On the strictest definitions of utility I could imagine, this would be the most analytically optimal thing.  Of course, that is for now, until I hear of another idea that could be 10x to 100x as "optimal" as this one.</p>
<p style="text-align:center;"><a href="http://bowlabs.files.wordpress.com/2013/05/line3.png"><img class="size-full wp-image-814 aligncenter" alt="line3" src="http://bowlabs.files.wordpress.com/2013/05/line3.png" width="700" height="128" /></a></p>
<p style="text-align:left;">But of course, essentially all people reject this final bit.  The wire heading promoters will say that they are promoting the best outcome (and thus are doing by far the most efficient utilitarian work), and claim that the "terminator" scenario is morally apprehensible because of how wrong it <em>feels </em>in comparison.   The uploading enthusiasts will promote theirs as the best outcome while claiming that the wire heading outcome is unnatural and obviously wrong.  The human utopians will promote theirs as the best outcome while claiming that human uploading is un-human in comparison.  And local charity enthusiasts will insist that their work is the best, and the intuitive good feelings it provides would be missed by the "effective altruists", and thus would wouldn't be reasonable.</p>
<p style="text-align:left;">Also, I'll note that quite a few people in the field of futuristic high-technology "effective altruism" are very much intent on themselves being a part of this.  That they themselves would get to live forever or be uploaded.  When asked why they prefer this to something that could mathematically produce much higher expected value, I hear answers like "this is already good enough!"  But how do we possibly decide rationally what "good enough" means, especially when there is something obvious better?</p>
<p style="text-align:left;">The great difficulty here, as I see it, is that the extreme moral stance, with as little intuition as possible, seems to be the terminator scenario or similar, areas that seems completely morally strange and unintuitive to absolutely everybody.  But if one were to do more "reasonable" things, one may make order-of-magnitude losses in efficiency for the sake of achieving a more intuitive answer, which was the entire problem we started out against.  We could make a trade-off in between (like many I know do), but such a trade-off would also be an intuitive one.</p>
<p style="text-align:center;"><a href="http://bowlabs.files.wordpress.com/2013/05/second.png"><img class="wp-image-813 aligncenter" alt="second" src="http://bowlabs.files.wordpress.com/2013/05/second.png" width="389" height="329" /></a></p>
<p style="text-align:left;"><b>Where to Go From Here</b></p>
<p style="text-align:left;">If one does accept some intuitive limitations from terminator support (or other intuitive options like keeping 10% of income because it "feels right"), at least we could admit it and realize that we aren't that much different from those "inefficient altruists" or even "regular people" who make different intuitive limitations than we do.  This is in many ways moral relativism and leads to a vague and somewhat frustrated form of morality, but at least not a hypocritical one.  Being honest to ourselves is a good first step.</p>
<p style="text-align:left;">I believe that really finding a rational ends that we can agree upon will take quite a bit of change to our own intuitions   It may just be a matter of time, like it was to get reduce other limitions (nationalism, sexism, racism, etc).  Of course, the issue is that the time required may be longer than available before apocalyptic / world changing event, so it is quite likely this will never be settled.</p>
<p style="text-align:left;">I do believe that this should be figured out and discussed much more rigorously.  Because from what I've seen, many of <strong><em>the most important</em></strong> moral issues are still surrounded by relatively emotional and intutive debate.  And for us being "rationality nerds", this is quite a huge deal.</p>
